import logging

from google import genai
from google.genai import types

from src.agent.prompts import ANALYZE_SYSTEM, ANALYZE_TOOL, ANALYZE_TOOL_CONFIG, ANALYZE_USER
from src.agent.state import PRReviewState
from src.github.client import GitHubClient
from src.github.diff import process_diff

logger = logging.getLogger(__name__)

SEVERITY_ICONS = {"high": "\U0001f534 High", "medium": "\U0001f7e1 Medium", "low": "\U0001f7e2 Low"}
DECISION_THRESHOLDS = {"high": "REQUEST_CHANGES", "medium": "COMMENT", "low": "APPROVE"}


async def fetch_diff(state: PRReviewState, *, github: GitHubClient) -> dict:
    """Fetch PR files from GitHub and process the diff."""
    files = await github.get_pr_files(state["repo"], state["pr_number"])
    result = process_diff(files)

    return {
        "diff": result.combined_diff,
        "changed_files": result.included_files,
        "skipped_files": result.skipped_files,
    }


async def analyze_code(state: PRReviewState, *, llm: genai.Client) -> dict:
    """Analyze the diff using Gemini with function calling for structured output."""
    user_prompt = ANALYZE_USER.format(
        pr_title=state["pr_title"],
        pr_description=state.get("pr_description", ""),
        changed_files=", ".join(state.get("changed_files", [])),
        diff=state["diff"],
    )

    response = await llm.aio.models.generate_content(
        model="gemini-2.0-flash",
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=ANALYZE_SYSTEM,
            tools=[ANALYZE_TOOL],
            tool_config=ANALYZE_TOOL_CONFIG,
        ),
    )

    # Extract the function call result
    for part in response.candidates[0].content.parts:
        if part.function_call and part.function_call.name == "submit_review":
            args = part.function_call.args
            return {
                "issues": args.get("issues", []),
                "suggestions": args.get("suggestions", []),
                "summary": args.get("summary", ""),
            }

    logger.warning("No function call in LLM response, returning empty analysis")
    return {"issues": [], "suggestions": [], "summary": "Analysis could not be completed."}


def format_review(state: PRReviewState) -> dict:
    """Format structured analysis into a Markdown review body."""
    issues = state.get("issues", [])
    suggestions = state.get("suggestions", [])
    summary = state.get("summary", "")
    skipped = state.get("skipped_files", [])

    # Determine decision based on highest severity issue
    max_severity = "low"
    for issue in issues:
        sev = issue.get("severity", "low")
        if sev == "high":
            max_severity = "high"
            break
        if sev == "medium":
            max_severity = "medium"

    decision = DECISION_THRESHOLDS[max_severity]

    parts = ["## \U0001f916 AI Code Review", ""]

    # Decision
    decision_label = {
        "APPROVE": "\u2705 APPROVE",
        "COMMENT": "\U0001f4ac COMMENT",
        "REQUEST_CHANGES": "\u274c REQUEST_CHANGES",
    }
    parts.append(f"**Decision: {decision_label.get(decision, decision)}**")
    parts.append("")

    # Issues
    if issues:
        parts.append("### \u2757 Issues")
        parts.append("")
        parts.append("| Severity | File | Issue |")
        parts.append("|----------|------|-------|")
        for issue in issues:
            icon = SEVERITY_ICONS.get(issue["severity"], issue["severity"])
            parts.append(f"| {icon} | `{issue['file']}` | {issue['message']} |")
        parts.append("")

    # Suggestions
    if suggestions:
        parts.append("### \U0001f4a1 Suggestions")
        parts.append("")
        for s in suggestions:
            parts.append(f"- `{s['file']}`: {s['suggestion']}")
        parts.append("")

    # Summary
    if summary:
        parts.append("### \U0001f4dd Summary")
        parts.append("")
        parts.append(summary)
        parts.append("")

    # Skipped files notice
    if skipped:
        parts.append(f"---\n> \u26a0\ufe0f **Note**: {len(skipped)} file(s) were skipped "
                      "(lockfiles, generated files, or exceeded token budget).")
        parts.append("")

    parts.append("---")
    parts.append("*Generated by [PR Sentinel](https://github.com/Pin-Han/pr-sentinel)*")

    return {
        "review_body": "\n".join(parts),
        "review_decision": decision,
    }


async def post_review(state: PRReviewState, *, github: GitHubClient) -> dict:
    """Post the review to the GitHub PR."""
    await github.post_review(
        repo=state["repo"],
        pr_number=state["pr_number"],
        body=state["review_body"],
        event=state["review_decision"],
    )
    logger.info(
        "Posted review on %s #%d (decision: %s)",
        state["repo"],
        state["pr_number"],
        state["review_decision"],
    )
    return {}
